### PR TITLE
Test on Ruby 2.3.1 on Travis CI

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
Oops, some tests for old Rubies are failing.
I'm now investigating.

**Comment by tricknotes** [comment]
Now all tests are passed on Travis CI 💚

**Comment by reed** [comment]
Thanks for submitting.  I'm out of town for the weekend, so I'll review this when I get back.

**Comment by reed** [comment]
Would you mind rebasing this PR into a single commit?

**Comment by tricknotes** [comment]
done.

**Comment by reed** [comment]
Thanks.  Sorry for the delay.

**Pull request merged**
